language: node_js
sudo: false
node_js:
  - "6.10"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm update
script:
  - node run gulp all-non-e2e
after_success: npm run gulp coverage
