language: node_js
sudo: false
node_js:
  - "6.10"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
install:
  - npm install
  - npm update
script:
  - node node_modules/gulp/bin/gulp.js backend-test
after_success: npm run coverage
